name: open_meteo_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
