name: weather_repository
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  open_meteo_api:
    path: ../open_meteo_api
  

dev_dependencies:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  coverage: ^1.0.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
